name: go

on:
  - push

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '^1.22.1'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: run test
        run: |
          make test
